name: CI

on: [push]

permissions:
  contents: read

jobs:

  lint:

    name: Lint
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Lint newlines
        uses: fionn/newline-linter@v1.0.2

      - name: Lint Go
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0

      - name: Check formatting
        run: test -z "$(gofmt -l .)"

      - name: Check dependency tidiness
        run: go mod tidy -diff

  test:

    name: Test
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Download dependencies
        run: go mod download

      - name: Test
        run: make test
